iri_wam:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort Joint Trajectory Controller ---------------------------------------
  iri_wam_controller:
    type: "effort_controllers/JointTrajectoryController" 
    joints:
      - iri_wam_joint_1 
      - iri_wam_joint_2
      - iri_wam_joint_3
      - iri_wam_joint_4
      - iri_wam_joint_5
      - iri_wam_joint_6
      - iri_wam_joint_7
    constraints:
      goal_time: 100.0
      stopped_velocity_tolerance: 0.02
      iri_wam_joint_1:
        goal: 0.02
      iri_wam_joint_2:
        goal: 0.02
      iri_wam_joint_3:
        goal: 0.02
      iri_wam_joint_4:
        goal: 0.02
      iri_wam_joint_5:
        goal: 0.02
      iri_wam_joint_6:
        goal: 0.02
      iri_wam_joint_7:
        goal: 0.02
    gains:
      iri_wam_joint_1: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
      iri_wam_joint_2: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
      iri_wam_joint_3: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
      iri_wam_joint_4: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
      iri_wam_joint_5: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
      iri_wam_joint_6: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
      iri_wam_joint_7: {p: 40000.0, i: 200.0, d: 0.0, i_clamp: 0.0}
    state_publish_rate: 50
    action_monitor_rate: 30
    stop_trajectory_duration: 0

  # Individual Joint Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_1
    pid: {p: 40000.0, i: 200.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_2
    pid: {p: 40000.0, i: 200.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_3
    pid: {p: 40000.0, i: 200.0, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_4
    pid: {p: 40000.0, i: 200.0, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_5
    pid: {p: 40000.0, i: 200.0, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_6
    pid: {p: 40000.0, i: 200.0, d: 0.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: iri_wam_joint_7
    pid: {p: 40000.0, i: 200.0, d: 0.0}
